AMELIA NUR HUMAIROH 
   / 2208541016

# 5.16 LIST 2 DIMENSI

  List dua dimensi dalam phyton dikatakan sebagai suatu list berisi list lagi ,biasanya untuk mepresentasikan matriks menggunakan list dua dimensi ini. sedangkan list dalam pemrograman phyton sendiri bisa dikatakan sebagai struktur data yang paling dasar adalah urutan atau list,dan juga setiap elemen-elemennya berurutan akan diberi nomor posisi atau indeksnya.Indeks pertama dalam list dimulai dari nol, satu, dua, tiga dan seterusnya.
  

In [5]:
# input terlebih dulu matriks yang kita ingin jalankan.
# ingat untuk mengakses dalam list phyton,gunakan tada kurung siku untuk mengiris beserta indeks,atau untuk mendapatkan nilai yang tersedia pada indeks tersebut.
matriks = [
    [5,0,8],
    [2,6,7],
    [1,3,4],
]
print(matriks) 
#mencetak semua indeks data yang ada pada matriks
matriks[1]
#mencetak  indeks baris ke 2 (dimulai dari 2,6,7)

[[5, 0, 8], [2, 6, 7], [1, 3, 4]]


[2, 6, 7]

In [7]:
#mengikuti input matriks yang pertama pada contoh selanjutnya 
matriks[1][2]  #mencetak indeks data yang berasal dari baris ke 2 kolom ke 3

[[5, 0, 8], [2, 6, 7], [1, 3, 4]]

In [8]:
matriks
#mencetak semua indeks data yg di panggil

[[5, 0, 8], [2, 6, 7], [1, 3, 4]]

In [10]:
matriks[1][2]=200
print(matriks[1][2])
#mengganti indeks data pada matriks baris ke dua kolom ke 3 dengan data 200

200


In [11]:
for baris in matriks:
    print (baris)
    for kolom in baris:
        print (kolom)
#memanggil anggota dari list 2 dimensi dengan model baris pada matriks,dan kolom pada baris.

[5, 0, 8]
5
0
8
[2, 6, 200]
2
6
200
[1, 3, 4]
1
3
4


# 5.17 TUPLES

In [15]:
#input indeks data terlebih dahulu yang ingin dijalankan.
#pada tuple dapat memasukkan nila-nilai yang dipisahkan koma di antara tanda kurung juga.
#pada tuple juga sama yaitu nilai-nilainya dimulai dari nol,satu dua dan seterusnya.
nilai = (100,90,50,60,70)
print(nilai[0])           #mencetak nilai data pada urutan 0
print(nilai[0:4])         #mencetak nilai data mulai urutan 0 sampai batas 4,tapi 4 tidak ikut dicetak.

100
(100, 90, 50, 60)


In [24]:
nilai[0] = 200
#aksi seperti ini tidak bisa dilakukan pada tuple phyton,karena memang nilai pada tuple phyton tidak dapat di ubah.
#jadi jika ingin maka buatlah tuple baru
#maka tidak akan muncul nilainya 

TypeError: 'tuple' object does not support item assignment

In [27]:
nilai.append(100)
#tidak akan munculnilainya karena benar tidak bisa pada tuple phyton.

AttributeError: 'tuple' object has no attribute 'append'

In [30]:
nilai.index(4) #tidak ada pada indeks tuple phyton,maka benar tidak bisa muncul hasilnya. (error)

ValueError: tuple.index(x): x not in tuple

In [ ]:
nilai.remove (3) #pada tuple tidak ada objek untuk remove
#jika ingin menghapus menggunakan statement (del)
#lalu buat kembali tuple yang diinginkan.

In [ ]:
del nilai

In [40]:
#jika sudah terhapus buat kembali tuple baru dengan elemen yang diinginkan
tuple = ('buku', 'kimia',2023)
print ("setelah menghapus nilai :", tuple)
#maka akan muncul indeks data tuple lagi yang sudah kita input baru.

setelah menghapus nilai : ('buku', 'kimia', 2023)


# 5. 18 DICTIONARIES

 Dictionaries Phyton berbeda dengan list ataupun tuples, karena setiap urutannya berisi key dan value,setiap key dipisahkan dari valuenya oleh titik dua (:), setiap data/nilainya dipisahkan oleh koma, dan semuanya tertutup dalam kurung kurawal.Dictionaries digunakan jika datanya terkait satu sama lain.

In [50]:
#masukkan indeks data yang ingin kita jalankan
data_mahasiswa= {
    "nama" : "Amelia",
    "umur"  : 18,
    "Fakultas" : "Fmipa"
}

In [57]:
print(data_mahasiswa['nama'])
print(data_mahasiswa.get ('nama')) #mencetak nama yang dinginkan
print(data_mahasiswa.get('tanggal_lahir', '9-7-2004')) #menambah cetak tanggal lahir pada data yang dijalankan
print(data_mahasiswa)              #mencetak data mahasiswa pada indeks yang dijalankan.
data_mahasiswa ['HP'] = '085804431002' #menambah indeks data (hp) pada data yang kita jalankan
print(data_mahasiswa['HP'])
print(data_mahasiswa) #mencetak data yang terbaru dengan tambahan nomor hp yang kita massukkan.

Amelia
Amelia
9-7-2004
{'nama': 'Amelia', 'umur': 18, 'Fakultas': 'Fmipa', 'HP': '085804431002'}
085804431002
{'nama': 'Amelia', 'umur': 18, 'Fakultas': 'Fmipa', 'HP': '085804431002'}


In [68]:
#contoh mengubah dari angka menjadi kata,
#masukan dulu input yang diinginkan
angka ={
    '0'     : "nol",
    '1'     : 'satu',
    '2'     : 'dua',
    '3'     : 'tiga',
    '4'     : 'empat',
    '5'     : "lima",
}

In [69]:
#ingin menjalankan indeks data mengubah angka menjadi kata /huruf dengan input di atas
daftar_harga = input('Masukkan nomor meja anda ')
nomor_angka = ""
for isi in daftar_harga :
    nomor_angka += angka.get(isi) + " "
print(nomor_angka)

Masukkan nomor meja anda 4
empat 


# 5.19 FUNGSI DALAM PHYTON

 Fungsi adalah kumpulan perintah atau baris kode yang dikelompokkan menjadi satu kesatuan untuk kemudian bisa di panggil atau digunakan berkali-kali.
#sebuah fungsi bisa menerima parameter,bisa mengembalikan suatu nilai,dan juga bisa dipanggil berkali-kali secara independen.
#fugsi blok dimulai dengan "def" kata kunci diikuti oleh nama fungsi dan tanda kurung().
#Blok kode dalam setiap fungsi dimulai dengan titik dua(:)
#setiap parameter yang ingin dimausukkan harus berada di dalam tanda kurung.

In [74]:
#contoh memanggil fungsi
def perkenalan (nama, asal):
    print(f"Perkenalkan saya {nama} dari {asal}")
perkenalan("Amelia nur humairoh", "Jawa timur")

Perkenalkan saya Amelia nur humairoh dari Jawa timur


In [3]:
#masukkan fungsi yang mau kita jalankan terlebih dahulu
def mobil():
    print('Toyota Rush')
    
def harga():
    print('Harga Toyota Rush 2023 Rp. 305.000.000')

mobil()  #memanggil fungsi mobil
harga()  # memanggil fungsi harga

Toyota Rush
Harga Toyota Rush 2023 Rp. 305.000.000


In [5]:
#contoh untuk ingin mencetak data siswa 
nama = "Amelia Nur"
umur = 18
kelas = "12 mipa 2"
nilai = 88

print( "Nama  :", nama)
print( "Umur  :", umur, "tahun")
print( "Kelas :", kelas)
print( "Nilai :", nilai)

Nama  : Amelia Nur
Umur  : 18 tahun
Kelas : 12 mipa 2
Nilai : 88


In [7]:
#contoh untuk mencetak data dengan kode seperti diatas tetapi dengan jummlah lebih banyak siswa yang lain.
#deklarasi fungsi 'data_siswa'
def data_siswa(nama, umur, kelas, nilai):
    print( "Nama  :", nama)
    print( "Umur  :", umur, "tahun")
    print( "Kelas :", kelas)
    print( "Nilai :", nilai)
    print()  # untuk menambah baris kosong
    
#memanggil fungsi 'data_siswa'
data_siswa("Putri", 18, "12 ips 2", 78)
data_siswa("Dandi", 18, "12 mipa 1", 92)
data_siswa("Dewi", 17, "10 mipa 2", 88)

Nama  : Putri
Umur  : 18 tahun
Kelas : 12 ips 2
Nilai : 78

Nama  : Dandi
Umur  : 18 tahun
Kelas : 12 mipa 1
Nilai : 92

Nama  : Dewi
Umur  : 17 tahun
Kelas : 10 mipa 2
Nilai : 88



In [9]:
#contoh untuk deklarasi fungsi 'data-siswa' ditambah dengan predikatnya
def data_siswa(nama, umur, kelas, nilai):
#lalu kita juga bisa membuat dulu predikat nilainya
    predikat = ''
    if nilai > 90:
        predikat = 'A'
    elif nilai > 80:
        predikat = 'B'
    elif nilai > 70:
        predikat = 'C'
    else:
        predikat = 'D'
    
    print( "Nama     :", nama)
    print( "Umur     :", umur, "tahun")
    print( "Kelas    :", kelas)
    print( "Nilai    :", nilai)
    print( "Predikat :", predikat)
    print()  # untuk menambah baris kosong
    
#memanggil fungsi 'data_siswa'
data_siswa("Putri", 18, "12 ips 2", 78)
data_siswa("Dandi", 18, "12 mipa 1", 92)
data_siswa("Dewi", 17, "10 mipa 2", 88)

Nama     : Putri
Umur     : 18 tahun
Kelas    : 12 ips 2
Nilai    : 78
Predikat : C

Nama     : Dandi
Umur     : 18 tahun
Kelas    : 12 mipa 1
Nilai    : 92
Predikat : A

Nama     : Dewi
Umur     : 17 tahun
Kelas    : 10 mipa 2
Nilai    : 88
Predikat : B



# 5. 20 NUMPY

 Numpy (Numerical Phyton) adalah library Phyton yang fokus pada scientific computing. Numpy menyediakan fungsi yang siap pakai untuk memudahkan kita melakukan perhitungan saintifik seperti matriks,aljabar,statistik,dan sebagainya.

In [10]:
 import numpy as np

# 5.20.1 Perintah dasar pada Numpy

In [21]:
#masukkan dulu indeks yang ingin dijalankan
x =np.array ([0,1,2,3,4,5,6,])
print (x)     #memanggil data seperti biasanya
print()       # membuat baris kosong
y=np.array ([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print (y)

[0 1 2 3 4 5 6]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [22]:
x.ndim

1

In [23]:
y.ndim

2

In [24]:
x.shape

(7,)

# 5.20.2 Memanggil anggota,kolom dan baris dengan Numpy

In [29]:
#contoh memanggil pada matriks
#ingat list array itu indeksnya selalu dimulai dari nol.

matriks_np = np.array([[1,2,3],
                       [4,5,6],
                       [7,8,9]])
print(matriks_np[1][1]) #mau memanggil angka yang beradadikolom ke -1 dan bari ke-1
print()
print(matriks_np)       #memanggil semua data yang ada pada matriks
print()
print(matriks_np [1,:]) #memanggil data pada baris 1

5

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[4 5 6]


In [30]:
#membuat array
nilai_siswa = np.array([70, 78, 90, 88])
print(nilai_siswa)
print(nilai_siswa[3]) # ingin memanggil data pada array nilai ke (3)

[70 78 90 88]
88


# 5.20.3 Matriks pada Numpy

In [73]:
#contoh membuat matriks 
a = np.zeros((5,5))
print(a) #mencetak matriks dengan 5 baris dan 5 kolom
print()
b= np.identity(8) #mencetak matriks dengan identitasnya ada 8
print(b)
print()
c=6*b
print(c) #mengganti identitas 1 dengan 6

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

[[6. 0. 0. 0. 0. 0. 0. 0.]
 [0. 6. 0. 0. 0. 0. 0. 0.]
 [0. 0. 6. 0. 0. 0. 0. 0.]
 [0. 0. 0. 6. 0. 0. 0. 0.]
 [0. 0. 0. 0. 6. 0. 0. 0.]
 [0. 0. 0. 0. 0. 6. 0. 0.]
 [0. 0. 0. 0. 0. 0. 6. 0.]
 [0. 0. 0. 0. 0. 0. 0. 6.]]


# 5.20.4 Copy pada Numpy

Copy memiliki data dan perubahan apapun yang dilakukan pada copy tidak akan memengaruhi array asli, dan perubahan apa pun yang dibuat pada array asli tidak akan memengaruhi copy.

In [36]:
#masukkan dulu indeks yang ingin dijalankan
x =np.array ([0,1,2,3,4,5,6,])
print (x)    #memanggil data seperti biasanya
print()      #membuat baris kosong

y=x
print (y)    #jika nilai y = x bisa langsung memanggil dengan kode y=x

z = np.array([5,6,7,8,9])
print(z)
q = z.copy() #langsung mengkopi data bila q = z
q[0] = 10    #mengganti nilai 0 dengan 10 pada indeks q 
print (q)

[0 1 2 3 4 5 6]

[0 1 2 3 4 5 6]
[5 6 7 8 9]
[10  6  7  8  9]


# 5.20.5 Operasi Matematika pada Numpy

In [38]:
#contoh untuk menggunakan operasi sin,cos,tan 
import math
radian = math.radians(45.0)
hasil_sinus =math.sin(radian)
hasil_cosinus =math.cos(radian)
hasil_tangen =math.tan(radian)

print("hasil sinus 45 derajat adalah ", hasil_sinus)
print("hasil cosinus 45 derajat adalah ", hasil_cosinus)
print("hasil tangen 45 derajat adalah ", hasil_tangen)

hasil sinus 45 derajat adalah  0.7071067811865476
hasil cosinus 45 derajat adalah  0.7071067811865476
hasil tangen 45 derajat adalah  0.9999999999999999


In [43]:
#masukkan dulu indeks yang ingin dijalankan
x =np.array ([0,1,2,3,4,5,6,])
y = np.array([5,6,7,8,9])

x-2 #pada matriks nilainya berkurang 2

array([-2, -1,  0,  1,  2,  3,  4])

In [44]:
y*2 #pada matriks y nilainya dikalikan 2

array([10, 12, 14, 16, 18])

In [45]:
np.cos(x) #nilai cosinus untuk matriks x

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029])

# 5.20.6 Perkalian Matriks pada Numpy

In [53]:
#masukkan dulu indeks yang ingin dijalankan
A= [[6,7],
    [8,9]]

B= [[1,3],
    [5,7]]
print(np.dot(A,B)) #bisa menggunakan kode ini untu mengalikan matriks AB
print()
print(np.matmul(A,B)) #kode ini juga sama dengan dot di atas


[[41 67]
 [53 87]]

[[41 67]
 [53 87]]


# 5.20.7 Min, Max dan Sum pada Numpy

In [62]:
#contoh 1
matriks =np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(matriks)
print()            #membuat baris kosong
A= np.min(matriks) #kode mengakses min pada matriks
print(A)
print()            #membuat baris kosong
B=np.min(matriks,axis=0) #mencetak matriks 0
print(B)
print()
C=np.max(matriks)  #kode mengakses max pada matriks
print(C)
print()
D=np.sum(matriks)  #kode mengangkes sum pada matriks
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

1

[1 2 3]

9

45


In [66]:
#contoh 2
#masukkan dulu indeks yang ingin dijalankan

nilai = np.array([80,50,60,75,90,55])
print('Nilai minimalnya adalah = ',nilai.min())
print('Nilai maksimalnya adalah = ',nilai.max())
print('Nilai rata-ratanya adalah = ',nilai.mean())
print('Jumlah Nilainya adalah = ',nilai.sum())

Nilai minimalnya adalah =  50
Nilai maksimalnya adalah =  90
Nilai rata-ratanya adalah =  68.33333333333333
Jumlah Nilainya adalah =  410
